fun main() {
    println("Enter the following: ")
    print("Enrollment Number: ")
    var en = readLine()
    print("Student Name: ")
    var sn = readLine()
    print("Student Branch: ")
    var sb = readLine()
    print("Student Class: ")
    var sc = readLine()
    print("Student Batch: ")
    var sba = readLine()
    print("Student Collage Name: ")
    var scn = readLine()
    print("Student University Name: ")
    var sun = readLine()
    print("Student Age: ")
    var sa = readLine()

    println("*************************")
    println("Student's Information")
    println("Enrollment No : " + en)
    println("Name : " + sn)
    println("Age : " + sa)
    println("Branch : " + sb)
    println("Class : " + sc)
    println("Batch : " + sba)
    println("Collage Name : " + scn)
    println("University Name : " + sun)

}